# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#d9e6e2"

# Title color for boxes
theme[title]="#d9e6e2"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#20b2aa"

# Background color of selected item in processes box
theme[selected_bg]="#3d5d6d"

# Foreground color of selected item in processes box
theme[selected_fg]="#20b2aa"

# Color of inactive/disabled text
theme[inactive_fg]="#3d5d6d"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#d9e6e2"

# Background color of the percentage meters
theme[meter_bg]="#3d5d6d"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d9e6e2"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#bf7fff"
theme[mem_box]="#90ee90"
theme[net_box]="#b22222"
theme[proc_box]="#20b2aa"

# Box divider line and small boxes line color
theme[div_line]="#3d5d6d"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#90ee90"
theme[temp_mid]="#7fff00"
theme[temp_end]="#b22222"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#00cdcd"
theme[cpu_mid]="#80a0ff"
theme[cpu_end]="#bf7fff"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#bf7fff"
theme[free_mid]="#80a0ff"
theme[free_end]="#00cdcd"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#80a0ff"
theme[cached_mid]="#00cdcd"
theme[cached_end]="#bf7fff"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#7fff00"
theme[available_mid]="#b22222"
theme[available_end]="#b22222"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#90ee90"
theme[used_mid]="#00cdcd"
theme[used_end]="#80a0ff"

# Download graph colors (Peach -> Red)
theme[download_start]="#7fff00"
theme[download_mid]="#b22222"
theme[download_end]="#b22222"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#90ee90"
theme[upload_mid]="#00cdcd"
theme[upload_end]="#80a0ff"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#00cdcd"
theme[process_mid]="#80a0ff"
theme[process_end]="#bf7fff"
