general {
    lock_cmd = omd-lock
    before_sleep_cmd = OMD_LOCK_ONLY=true omd-lock
    after_sleep_cmd = sleep 1 && omd-wake
    inhibit_sleep = 3                                      # wait until screen is locked
}

# Start screensaver after 2.5 minutes
listener {
    timeout = 150
    on-timeout = pidof hyprlock || hyprlock --config ~/.config/omd/hypr/hyprlock.conf
}

# Lock system after 5 minutes (screensaver resets idle timer, so have to just do half + 2s margin)
listener {
    timeout = 152
    on-timeout = omd-lock
    on-resume = omd-wake
}
