source = ~/.config/omd/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = screenshot
    blur_passes = 4
    blur_size = 8
}

animations {
    enabled = false
}

# Date Label
label {
    monitor =
    text = cmd[update:1000] date +"%A, %B %d"
    color = rgba(214, 214, 214, 1.0)
    font_size = 20
    font_family = Cantarell
    position = 0, -80
    halign = center
    valign = top
}

# Time Label
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(242, 242, 242, 1.0)
    font_size = 86
    font_family = Cantarell Bold
    position = 0, -120
    halign = center
    valign = top
}

# User Label
label {
    monitor =
    text = $USER
    color = rgba(238, 238, 238, 1.0)
    font_size = 18
    font_family = Cantarell Medium
    position = 0, 24
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 34
    position = 0, -20
    halign = center
    valign = center

    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(0, 0, 0, 0)
    outline_thickness = 0

    font_family = Cantarell
    font_color = $font_color

    placeholder_text = <span foreground="##a8a8a8">Password</span>
    check_color = rgba(0, 0, 0, 0)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false

    dots_center = true
    dots_size = 0.25
    dots_spacing = 0.3

    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    swap_font_color = false
}

auth {
    fingerprint:enabled = false
}

source = ~/.local/state/omd/toggles/hyprlock.conf
