[colors.primary]
background = "#000000"
foreground = "#d9e6e2"

[colors.cursor]
text = "#000000"
cursor = "#7ec0ee"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#7ec0ee"

[colors.search.matches]
foreground = "#000000"
background = "#7fff00"

[colors.search.focused_match]
foreground = "#000000"
background = "#b22222"

[colors.footer_bar]
foreground = "#000000"
background = "#d9e6e2"

[colors.selection]
text = "#000000"
background = "#80a0ff"

[colors.normal]
black = "#000000"
red = "#b22222"
green = "#90ee90"
yellow = "#7fff00"
blue = "#80a0ff"
magenta = "#bf7fff"
cyan = "#00cdcd"
white = "#d9e6e2"

[colors.bright]
black = "#3d5d6d"
red = "#ff3030"
green = "#00ff7f"
yellow = "#b0e2ff"
blue = "#87cefa"
magenta = "#ab82ff"
cyan = "#40e0d0"
white = "#ffffff"
