background = #000000
foreground = #d9e6e2
cursor-color = #7ec0ee
selection-background = #80a0ff
selection-foreground = #000000

palette = 0=#000000
palette = 1=#b22222
palette = 2=#90ee90
palette = 3=#7fff00
palette = 4=#80a0ff
palette = 5=#bf7fff
palette = 6=#00cdcd
palette = 7=#d9e6e2
palette = 8=#3d5d6d
palette = 9=#ff3030
palette = 10=#00ff7f
palette = 11=#b0e2ff
palette = 12=#87cefa
palette = 13=#ab82ff
palette = 14=#40e0d0
palette = 15=#ffffff
